/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 octopus.gltf --transform
Author: henningrs (https://sketchfab.com/henningrs)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/octopus-873f8e6aa40d4b1ea878d4d5630c2851
Title: octopus
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/octopus-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.011}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <group position={[0, -0.8, -0.5]} rotation={[0.17, 0, 0]} scale={[0.49, 1, 0.38]}>
            <mesh geometry={nodes.Sphere001_Material003_0.geometry} material={materials['Material.003']} />
            <mesh geometry={nodes.Sphere001_Material001_0.geometry} material={materials['Material.001']} />
          </group>
          <group position={[0.8, 0, -0.5]} rotation={[0, 0.17, Math.PI / 2]} scale={[0.49, 1, 0.38]}>
            <mesh geometry={nodes.Sphere002_Material003_0.geometry} material={materials['Material.003']} />
            <mesh geometry={nodes.Sphere002_Material001_0.geometry} material={materials['Material.001']} />
          </group>
          <group position={[0, 0.8, -0.5]} rotation={[-0.17, 0, -Math.PI]} scale={[0.49, 1, 0.38]}>
            <mesh geometry={nodes.Sphere003_Material003_0.geometry} material={materials['Material.003']} />
            <mesh geometry={nodes.Sphere003_Material001_0.geometry} material={materials['Material.001']} />
          </group>
          <group position={[-0.8, 0, -0.5]} rotation={[0, -0.17, -Math.PI / 2]} scale={[0.49, 1, 0.38]}>
            <mesh geometry={nodes.Sphere004_Material003_0.geometry} material={materials['Material.003']} />
            <mesh geometry={nodes.Sphere004_Material001_0.geometry} material={materials['Material.001']} />
          </group>
          <group position={[0.6, -0.6, -0.5]} rotation={[0.12, 0.12, 0.78]} scale={[0.49, 1, 0.38]}>
            <mesh geometry={nodes.Sphere005_Material003_0.geometry} material={materials['Material.003']} />
            <mesh geometry={nodes.Sphere005_Material001_0.geometry} material={materials['Material.001']} />
          </group>
          <group position={[0.6, 0.6, -0.5]} rotation={[-0.12, 0.12, 2.36]} scale={[0.49, 1, 0.38]}>
            <mesh geometry={nodes.Sphere006_Material003_0.geometry} material={materials['Material.003']} />
            <mesh geometry={nodes.Sphere006_Material001_0.geometry} material={materials['Material.001']} />
          </group>
          <group position={[-0.6, 0.6, -0.5]} rotation={[-0.11, -0.13, -2.27]} scale={[0.49, 1, 0.38]}>
            <mesh geometry={nodes.Sphere007_Material003_0.geometry} material={materials['Material.003']} />
            <mesh geometry={nodes.Sphere007_Material001_0.geometry} material={materials['Material.001']} />
          </group>
          <group position={[-0.6, -0.6, -0.5]} rotation={[0.12, -0.12, -0.78]} scale={[0.49, 1, 0.38]}>
            <mesh geometry={nodes.Sphere008_Material003_0.geometry} material={materials['Material.003']} />
            <mesh geometry={nodes.Sphere008_Material001_0.geometry} material={materials['Material.001']} />
          </group>
          <mesh geometry={nodes.Sphere_Material001_0.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.Sphere009_Material002_0.geometry} material={materials['Material.002']} position={[0.36, -0.82, 0.23]} rotation={[1.46, 0, 0]} scale={0.17} />
          <mesh geometry={nodes.Torus_Material002_0.geometry} material={materials['Material.002']} position={[0, -0.98, 0.13]} rotation={[1.24, 0, 0]} scale={0.08} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/octopus-transformed.glb')
